version: 2
jobs:
  build:
    docker:
      - image: node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v2-{{ .Branch }}-
            - node-v2-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          name: Save NPM Package Cache
          key: node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - deploy:
          name: Deploy to branch gh-pages with "gh-pages" tool
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            npm run build
            npm run deploy-ci
      - run:
          name: Purge Cloudflare Cache
          command: npm run cloudflare-purge-cache

workflows:
  version: 2
  workflow:
    jobs:
    - build:
        filters:
          branches:
            only:
            - master