version: 2
jobs:
  build:
    docker:
      - image: node:8
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      # Run DEXON_BBS
      - restore_cache:
          name: Restore DEXON_BBS NPM Package Cache
          keys:
            - DEXON_BBS-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - DEXON_BBS-cache-v1-{{ .Branch }}-
            - DEXON_BBS-cache-v1-
      - run:
          name: Install DEXON_BBS Dependencies
          command: npm ci
      - save_cache:
          name: Save DEXON_BBS NPM Package Cache
          key: DEXON_BBS-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build DEXON_BBS
          command: npm run build

      # Run DEXON_BBS_Cache
      - restore_cache:
          name: Restore DEXON_BBS_Cache Yarn Package Cache
          keys:
            - DEXON_BBS_Cache-yarn-packages-v2-{{ .Branch }}-{{ checksum "./DEXON_BBS_Cache/yarn.lock" }}
            - DEXON_BBS_Cache-yarn-packages-v2-{{ .Branch }}-
            - DEXON_BBS_Cache-yarn-packages-v2-
      - run:
          name: Install DEXON_BBS_Cache Dependencies
          command: cd ./DEXON_BBS_Cache; yarn install --frozen-lockfile
      - save_cache:
          name: Save DEXON_BBS_Cache Yarn Package Cache
          key: DEXON_BBS_Cache-yarn-packages-2-{{ .Branch }}-{{ checksum "./DEXON_BBS_Cache/yarn.lock" }}
          paths:
            - ./DEXON_BBS_Cache/node_modules

      - restore_cache:
          name: Restore DEXON_BBS_Cache dist Cache
          keys:
            - DEXON_BBS_Cache-dist-cache-v3-{{ .Branch }}-{{ checksum "./build/cache.html" }}
            - DEXON_BBS_Cache-dist-cache-v3-{{ .Branch }}-
            - DEXON_BBS_Cache-dist-cache-v3-
      - run:
          name: Build DEXON_BBS_Cache
          command: |
            cd ./DEXON_BBS_Cache
            ln -s ../build gh-pages
            npm run cache
            cp -R ./dist/s gh-pages/
      - save_cache:
          name: Save DEXON_BBS_Cache dist Cache
          key: DEXON_BBS_Cache-dist-cache-v3-{{ .Branch }}-{{ checksum "./build/cache.html" }}
          paths:
            - ./DEXON_BBS_Cache/dist
      - deploy:
          name: Deploy to branch gh-pages with "gh-pages" tool
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            npm run deploy-ci
      - run:
          name: Cloudflare Purge Cache
          command: npm run cloudflare-purge-cache

workflows:
  version: 2
  workflow:
    jobs:
    - build:
        filters:
          branches:
            only:
            - master